name: Cypress API Test
on:
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-actions@v6
