name: Agendamento - Teste de API Cypress
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4
      - name: Executar o Cypress
        uses: cypress-io/github-action@v6
